### ISSUE TITLE
yarn store-metadata 実行時エラー

### ISSUE THREAD

**Issue by maruzyee** [0xhokusai/hokusai-get-started#7]
## Description
`yarn store-metadata` 実行時に以下のエラーが出ます。

```
> hokusai-get-started@1.0.0 store-metadata:run /Users/hikaru/local/src/hokusai-get-started
> node ./build/storeMetadata.js

/Users/hikaru/local/src/hokusai-get-started/node_modules/@web-std/fetch/dist/index.cjs:1534
                        response_?.emit("error", err);
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/hikaru/local/src/hokusai-get-started/node_modules/nft.storage/dist/src/token.cjs:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hokusai-get-started@1.0.0 store-metadata:run: `node ./build/storeMetadata.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hokusai-get-started@1.0.0 store-metadata:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hikaru/.npm/_logs/2021-10-09T05_49_19_667Z-debug.log
ERROR: "store-metadata:run" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## Reproduction

How reproduce this bug.

## How to fix

If you have any idea:)

**Comment by maruzyee** [comment]
nodeのバージョンをv12からv14 にあげることで解決しました。
